#!/bin/sh

TEST_IMAGE_TAG="k8s-analysis-test"
docker build -t "${TEST_IMAGE_TAG}:latest" .

test_Dockerfile() {
  for PRG in curl psql; do
    OUTPUT=$(docker run ${TEST_IMAGE_TAG}:latest ${PRG} --help)
    assertNotEquals " can't run ${PRG};" "${OUTPUT}" ""
  done
}

for DEPENDENCY in docker shunit2; do
  if [ -z $(which ${DEPENDENCY}) ]; then
    echo "Missing dependency '${DEPENDENCY}'"
    exit 1
  fi
done

. shunit2
