#!/bin/sh

TEST_IMAGE_NAME="k8s-analysis-test"
TEST_IMAGE_TAG="latest"
docker build -t "${TEST_IMAGE_NAME}:${TEST_IMAGE_TAG}" .

test_Dockerfile() {
  for PRG in curl psql; do
    OUTPUT=$(docker run --rm ${TEST_IMAGE_NAME}:${TEST_IMAGE_TAG} ${PRG} --help)
    assertNotEquals " can't run ${PRG};" "${OUTPUT}" ""
  done
  # cleanup
  docker rmi -f "${TEST_IMAGE_NAME}:${TEST_IMAGE_TAG}"
}

for DEPENDENCY in docker shunit2; do
  if [ -z $(which ${DEPENDENCY}) ]; then
    echo "Missing dependency '${DEPENDENCY}'"
    exit 1
  fi
done

. shunit2
